### ISSUE TITLE
Remove sentences with links to private `github/copilot-partners` repository

### ISSUE THREAD

**Issue by rajbos** [copilot-extensions/preview-sdk.js#64]
See the link to the `copilot-partners` repo here: https://github.com/copilot-extensions/preview-sdk.js/blob/2b498290a031fa3fbaad4cfdb76755f25318fdbb/README.md?plain=1#L225.

Not sure where that should point to.

**Comment by gr2m** [comment]
Oh good catch! The linked repository is private, that's why you get a 404.

I think for now we should remove these links. [We have public documentation now](https://docs.github.com/en/copilot/building-copilot-extensions/about-building-copilot-extensions) but there is no docs on the syntax for each of these event types

**Comment by francisfuzz** [comment]
Thanks again for opening this issue!

https://github.com/copilot-extensions/preview-sdk.js/commit/8c434bce3034752be8dd586645e8e9fce46e0b82 modified this to remove the reference in place of the appropriate documentation in the GitHub Docs. 

I think we're good to close this now! ⚡
